export const FETCH_CONSTRUCTORS = 'FETCH_CONSTRUCTORS';
export const FETCH_CONSTRUCTORS_SUCCESS = 'FETCH_CONSTRUCTORS_SUCCESS';
export const FETCH_DRIVERS = 'FETCH_DRIVERS';
export const FETCH_DRIVERS_SUCCESS = 'FETCH_DRIVERS_SUCCESS';
